### ISSUE TITLE
Validasi required form dengan Type Inputan Radio

### ISSUE THREAD

**Issue by jemifaisal** [arwahyu01/main-master#2]
Ketika di blade didefenisikan inputan 'required' di salah satu pilihan Radio, pesan error validasi formnya tidak terpenuhi jika yang dipilih pilihan yang tidak didefenisikan 'required'. 
Contoh: Surat Permohonan Aktif ?
`<input type="radio" name="surat_permohonan" id="surat_permohonan-1" class="filled-in chk-col-primary" value="1" required="required">
<label for="surat_permohonan-1">Ya</label>
<input type="radio" name="surat_permohonan" id="surat_permohonan-2" class="filled-in chk-col-primary" value="0">
<label for="surat_permohonan-2">Tidak</label>`

**Comment by arwahyu01** [comment]
oke, sudah saya perbaiki. terimakasih.
